version: '3'

services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: conradoroot
      MONGO_USER: conrado
      MONGO_PASSWORD: conrado
      MONGO_DATABASE: noderest
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo-net
    command: --auth

  rest:
    image: 'noderest'
    working_dir: /home/node
    environment:
      - NODE_ENV=development
      - MONGO_USER=conrado
      - MONGO_PASSWORD=conrado
    volumes:
      - ./:/home/node
    expose:
      - '3000'
    command: './start.sh'
    networks:
      - nginx-net
      - mongo-net

  proxy-reverso:
    image: nginx:latest
    volumes:
      - ./proxy_reverso/:/etc/nginx/conf.d/:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-net

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=conradoroot
    networks:
      - mongo-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - nginx-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3100:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - nginx-net

volumes:
  mongo_data:
  grafana_data:

networks:
  mongo-net:
  nginx-net:
